name: eureka_learn
description: Learning platform for all Cameroonians.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  animate_do: ^3.3.4
  animated_text_kit: ^4.2.1
  auto_route: ^9.2.2
  awesome_notifications: ^0.10.0
  bot_toast: ^4.0.1
  cached_network_image: ^3.2.0
  card_swiper: ^3.0.1
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.2
  dio: null
  enum_to_string: null
  equatable: null
  file_picker: ^8.1.7
  firebase_auth: ^4.16.0
  firebase_core: ^2.32.0
  firebase_dynamic_links: ^5.5.7
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.6.5
  flutter:
    sdk: flutter
  flutter_cached_pdfview: ^0.4.1
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.0.4
  flutter_riverpod: ^2.6.1
  flutter_shimmer: ^2.1.2
  flutterfire_ui: ^0.4.3+20
  font_awesome_flutter: ^10.8.0
  get: ^4.6.1
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.6.1
  html_character_entities: null
  iconsax: ^0.0.8
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.19.0
  like_button: ^2.0.4
  line_icons: ^2.0.1
  lottie: ^3.2.0
  percent_indicator: ^4.2.4
  share_plus: ^10.1.3
  shared_preferences: ^2.0.6
  syncfusion_flutter_charts: ^28.1.36
  syncfusion_flutter_pdfviewer: ^28.1.36
  timeago: ^3.1.0
  toggle_switch: ^2.3.0
  translator: ^1.0.3+1
  webview_flutter_plus: ^0.4.10

dev_dependencies:
  auto_route_generator: null
  build_runner: null
  flutter_test:
    sdk: flutter
 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/icons/jpeg/
    - assets/icons/png/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
