// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxBPsyzKupqgXO_lcrerv87V5Ex7N2UJ0',
    appId: '1:557552000377:web:6a3f1d8bed377dba3323a8',
    messagingSenderId: '557552000377',
    projectId: 'eurekalearn-d63d4',
    authDomain: 'eurekalearn-d63d4.firebaseapp.com',
    storageBucket: 'eurekalearn-d63d4.appspot.com',
    measurementId: 'G-5ZHGXKQCR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK9AsPIeCrV9eisQYsMthi-hGjdWMXxDY',
    appId: '1:557552000377:android:958927bd698e25453323a8',
    messagingSenderId: '557552000377',
    projectId: 'eurekalearn-d63d4',
    storageBucket: 'eurekalearn-d63d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQYj-eDIXbQNcH1QlJnd1EC3jAKr_m4SI',
    appId: '1:557552000377:ios:2e335af110f712fe3323a8',
    messagingSenderId: '557552000377',
    projectId: 'eurekalearn-d63d4',
    storageBucket: 'eurekalearn-d63d4.appspot.com',
    androidClientId: '557552000377-6rmlts1q6r7vpuqj0d7hps5o6m0amu35.apps.googleusercontent.com',
    iosClientId: '557552000377-10puqfnj84l25f014jil94l7rirl4e5j.apps.googleusercontent.com',
    iosBundleId: 'app.eurekalearn.com.eurekalearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQYj-eDIXbQNcH1QlJnd1EC3jAKr_m4SI',
    appId: '1:557552000377:ios:2e335af110f712fe3323a8',
    messagingSenderId: '557552000377',
    projectId: 'eurekalearn-d63d4',
    storageBucket: 'eurekalearn-d63d4.appspot.com',
    androidClientId: '557552000377-6rmlts1q6r7vpuqj0d7hps5o6m0amu35.apps.googleusercontent.com',
    iosClientId: '557552000377-10puqfnj84l25f014jil94l7rirl4e5j.apps.googleusercontent.com',
    iosBundleId: 'app.eurekalearn.com.eurekalearn',
  );
}
