// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ0KJyhupqvoMdgKQ3A_eTnG7G3z78b5o',
    appId: '1:23841223173:web:762a13e9d09fda6659e26c',
    messagingSenderId: '23841223173',
    projectId: 'eurekalearn-apps',
    authDomain: 'eurekalearn-apps.firebaseapp.com',
    storageBucket: 'eurekalearn-apps.appspot.com',
    measurementId: 'G-ZV31FRBDQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK8fx-vFDJyAItjRtVmu2NXXJ58G5XaeA',
    appId: '1:23841223173:android:8ee3eca077f9557159e26c',
    messagingSenderId: '23841223173',
    projectId: 'eurekalearn-apps',
    storageBucket: 'eurekalearn-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIj5yp3GIQyEnY-f_u64IOM0YNvX8d3Co',
    appId: '1:23841223173:ios:da71fa7e1207961159e26c',
    messagingSenderId: '23841223173',
    projectId: 'eurekalearn-apps',
    storageBucket: 'eurekalearn-apps.appspot.com',
    iosClientId: '23841223173-i56pm1b7vr3cgn4uv1k2of2vfc364t91.apps.googleusercontent.com',
    iosBundleId: 'com.example.eurekaLearn',
  );
}
